apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vikashsharma0707/malefashion-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/myntra"   # Yeh sahi hai
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"